# Generated by Django 4.0.5 on 2022-06-18 12:57

from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='')),
                ('year', models.IntegerField()),
                ('make', models.CharField(choices=[('Acura', 'Acura'), ('Audi', 'Audi'), ('BMW', 'BMW'), ('Buick', 'Buick'), ('Cadillac', 'Cadillac'), ('Chevrolet', 'Chevrolet'), ('Chrysler', 'Chrysler'), ('Dodge', 'Dodge'), ('Ford', 'Ford'), ('GMC', 'GMC'), ('Honda', 'Honda'), ('Hyundai', 'Hyundai'), ('INFINITI', 'INFINITI'), ('Jaguar', 'Jaguar'), ('Jeep', 'Jeep'), ('Kia', 'Kia'), ('Land Rover', 'Land Rover'), ('Lexus', 'Lexus'), ('Lincoln', 'Lincoln'), ('Mazda', 'Mazda'), ('Mercedes-Benz', 'Mercedes-Benz'), ('Mitsubishi', 'Mitsubishi'), ('Nissan', 'Nissan'), ('Porsche', 'Porsche'), ('RAM', 'RAM'), ('Subaru', 'Subaru'), ('Tesla', 'Tesla'), ('Toyota', 'Toyota'), ('Volkswagen', 'Volkswagen'), ('Volvo', 'Volvo')], max_length=128)),
                ('model', models.CharField(max_length=128)),
                ('body_style', models.CharField(choices=[('Cargo van', 'Cargo van'), ('Convertible', 'Convertible'), ('Coupe', 'Coupe'), ('Hatchback', 'Hatchback'), ('Minivan', 'Minivan'), ('Passenger van', 'Passenger van'), ('Pickup truck', 'Pickup truck'), ('SUV', 'SUV'), ('Sedan', 'Sedan'), ('Wagon', 'Wagon')], max_length=128)),
                ('exterior_color', models.CharField(max_length=128)),
                ('interior_color', models.CharField(max_length=128)),
                ('drivetrain', models.CharField(max_length=128)),
                ('transmission', models.CharField(max_length=128)),
                ('mileage', models.FloatField()),
                ('price', models.FloatField()),
                ('description', models.TextField()),
                ('date', models.DateTimeField(auto_now=True)),
                ('ordered', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['make'],
            },
        ),
        migrations.CreateModel(
            name='Engine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128)),
                ('fuel_type', models.CharField(choices=[('Diesel', 'Diesel'), ('Electric', 'Electric'), ('Gasoline', 'Gasoline'), ('Hybrid', 'Hybrid')], max_length=128)),
                ('displacement', models.FloatField()),
                ('power', models.FloatField()),
                ('price', models.FloatField()),
            ],
            options={
                'ordering': ('title',),
            },
        ),
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128)),
                ('price', models.FloatField()),
            ],
            options={
                'ordering': ('title',),
            },
        ),
        migrations.CreateModel(
            name='OrderedCar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.BigIntegerField(default=1)),
                ('total', models.FloatField(default=0)),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ordered_car', to='cars.car')),
                ('engine', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='selected_engine', to='cars.engine')),
                ('features', models.ManyToManyField(blank=True, related_name='selected_features', to='cars.feature')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.BigIntegerField(default=1)),
                ('first_name', models.CharField(max_length=128)),
                ('last_name', models.CharField(max_length=128)),
                ('email', models.EmailField(max_length=128)),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('total', models.FloatField(default=0)),
                ('cars', models.ManyToManyField(blank=True, related_name='ordered_cars', to='cars.orderedcar')),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='gallery')),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='cars.car')),
            ],
        ),
        migrations.AddField(
            model_name='car',
            name='compatible_engines',
            field=models.ManyToManyField(blank=True, related_name='compatible', to='cars.engine'),
        ),
        migrations.AddField(
            model_name='car',
            name='engine',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='standard', to='cars.engine'),
        ),
        migrations.AddField(
            model_name='car',
            name='extra_features',
            field=models.ManyToManyField(related_name='extra', to='cars.feature'),
        ),
        migrations.AddField(
            model_name='car',
            name='included_features',
            field=models.ManyToManyField(related_name='included', to='cars.feature'),
        ),
    ]
