# Generated by Django 4.0.5 on 2022-06-17 09:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='')),
                ('year', models.IntegerField()),
                ('make', models.CharField(max_length=128)),
                ('model', models.CharField(max_length=128)),
                ('body_style', models.CharField(max_length=128)),
                ('exterior_color', models.CharField(max_length=128)),
                ('interior_color', models.CharField(max_length=128)),
                ('drivetrain', models.CharField(max_length=128)),
                ('fuel_type', models.CharField(choices=[('Gasoline', 'Gasoline'), ('Diesel', 'Diesel'), ('Electric', 'Electric'), ('Hybrid', 'Hybrid')], max_length=128)),
                ('transmission', models.CharField(max_length=128)),
                ('engine', models.CharField(max_length=128)),
                ('engine_displacement', models.FloatField()),
                ('mileage', models.FloatField()),
                ('price', models.FloatField()),
                ('description', models.TextField()),
                ('date', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['date'],
            },
        ),
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128)),
                ('price', models.FloatField()),
            ],
            options={
                'ordering': ('title',),
            },
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='gallery')),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='cars.car')),
            ],
        ),
        migrations.AddField(
            model_name='car',
            name='extra_features',
            field=models.ManyToManyField(related_name='extra', to='cars.feature'),
        ),
        migrations.AddField(
            model_name='car',
            name='included_features',
            field=models.ManyToManyField(related_name='included', to='cars.feature'),
        ),
    ]
