# Generated by Django 4.0.5 on 2022-06-17 10:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Engine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128)),
                ('displacement', models.FloatField()),
                ('power', models.FloatField()),
                ('price', models.FloatField()),
            ],
            options={
                'ordering': ('title',),
            },
        ),
        migrations.RemoveField(
            model_name='car',
            name='engine_displacement',
        ),
        migrations.AlterField(
            model_name='car',
            name='body_style',
            field=models.CharField(choices=[('Cargo van', 'Cargo van'), ('Convertible', 'Convertible'), ('Coupe', 'Coupe'), ('Hatchback', 'Hatchback'), ('Minivan', 'Minivan'), ('Passenger van', 'Passenger van'), ('Pickup truck', 'Pickup truck'), ('SUV', 'SUV'), ('Sedan', 'Sedan'), ('Wagon', 'Wagon')], max_length=128),
        ),
        migrations.AlterField(
            model_name='car',
            name='fuel_type',
            field=models.CharField(choices=[('Diesel', 'Diesel'), ('Electric', 'Electric'), ('Gasoline', 'Gasoline'), ('Hybrid', 'Hybrid')], max_length=128),
        ),
        migrations.AlterField(
            model_name='car',
            name='make',
            field=models.CharField(choices=[('Acura', 'Acura'), ('Audi', 'Audi'), ('BMW', 'BMW'), ('Buick', 'Buick'), ('Cadillac', 'Cadillac'), ('Chevrolet', 'Chevrolet'), ('Chrysler', 'Chrysler'), ('Dodge', 'Dodge'), ('Ford', 'Ford'), ('GMC', 'GMC'), ('Honda', 'Honda'), ('Hyundai', 'Hyundai'), ('INFINITI', 'INFINITI'), ('Jaguar', 'Jaguar'), ('Jeep', 'Jeep'), ('Kia', 'Kia'), ('Land Rover', 'Land Rover'), ('Lexus', 'Lexus'), ('Lincoln', 'Lincoln'), ('Mazda', 'Mazda'), ('Mercedes-Benz', 'Mercedes-Benz'), ('Mitsubishi', 'Mitsubishi'), ('Nissan', 'Nissan'), ('Porsche', 'Porsche'), ('RAM', 'RAM'), ('Subaru', 'Subaru'), ('Tesla', 'Tesla'), ('Toyota', 'Toyota'), ('Volkswagen', 'Volkswagen'), ('Volvo', 'Volvo')], max_length=128),
        ),
        migrations.AddField(
            model_name='car',
            name='compatible_engines',
            field=models.ManyToManyField(related_name='compatible', to='cars.engine'),
        ),
        migrations.AlterField(
            model_name='car',
            name='engine',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='standart', to='cars.engine'),
        ),
    ]
