# Generated by Django 4.0.5 on 2022-06-16 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
