# Generated by Django 4.0.5 on 2022-06-16 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0003_alter_car_mileage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='engine_type',
            field=models.CharField(choices=[(1, 'Gasoline'), (2, 'Diesel')], max_length=128),
        ),
    ]
