# Generated by Django 4.0.5 on 2022-06-17 13:41

from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0003_remove_car_fuel_type_engine_fuel_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderedCar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ordered_car', to='cars.car')),
                ('chosen_engine', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='chosen', to='cars.engine')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=128)),
                ('last_name', models.CharField(max_length=128)),
                ('email', models.EmailField(max_length=254)),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('total', models.FloatField()),
                ('cars', models.ManyToManyField(related_name='ordered_cars', to='cars.orderedcar')),
            ],
        ),
    ]
