# Generated by Django 4.0.5 on 2022-06-17 14:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0004_orderedcar_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderedcar',
            name='chosen_engine',
        ),
        migrations.AddField(
            model_name='orderedcar',
            name='engine',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, related_name='selected_engine', to='cars.engine'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orderedcar',
            name='features',
            field=models.ManyToManyField(related_name='selected_features', to='cars.feature'),
        ),
    ]
