# Generated by Django 4.0.5 on 2022-06-16 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0004_alter_car_engine_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='engine',
            field=models.CharField(default='none', max_length=128),
            preserve_default=False,
        ),
    ]
