# Generated by Django 4.0.5 on 2022-06-17 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0005_remove_orderedcar_chosen_engine_orderedcar_engine_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='compatible_engines',
            field=models.ManyToManyField(blank=True, related_name='compatible', to='cars.engine'),
        ),
    ]
