# Generated by Django 4.0.5 on 2022-06-16 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0006_car_transmission'),
    ]

    operations = [
        migrations.RenameField(
            model_name='car',
            old_name='color',
            new_name='exterior_color',
        ),
        migrations.AddField(
            model_name='car',
            name='interior_color',
            field=models.CharField(default=1, max_length=128),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='car',
            name='engine_type',
            field=models.CharField(choices=[(1, 'Gasoline'), (2, 'Diesel'), (3, 'Electric')], max_length=128),
        ),
    ]
