# Generated by Django 4.0.5 on 2022-06-17 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0006_alter_car_compatible_engines'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderedcar',
            name='total',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
