# Generated by Django 4.0.5 on 2022-06-17 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0007_orderedcar_total'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='cars',
        ),
        migrations.AddField(
            model_name='order',
            name='order_number',
            field=models.BigIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='orderedcar',
            name='order_number',
            field=models.BigIntegerField(default=1),
        ),
    ]
