# Generated by Django 4.0.5 on 2022-06-17 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0008_remove_order_cars_order_order_number_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='order_number',
        ),
        migrations.RemoveField(
            model_name='orderedcar',
            name='order_number',
        ),
        migrations.AddField(
            model_name='order',
            name='session_key',
            field=models.CharField(default=1, max_length=128),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orderedcar',
            name='session_key',
            field=models.CharField(default=1, max_length=128),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='orderedcar',
            name='features',
            field=models.ManyToManyField(blank=True, related_name='selected_features', to='cars.feature'),
        ),
    ]
