# Generated by Django 4.0.5 on 2022-06-16 11:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0008_rename_option_feature_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='feature',
            options={'ordering': ('title',)},
        ),
    ]
