# Generated by Django 4.0.5 on 2022-06-17 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0009_remove_order_order_number_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='session_key',
        ),
        migrations.AddField(
            model_name='order',
            name='cars',
            field=models.ManyToManyField(blank=True, related_name='ordered_cars', to='cars.orderedcar'),
        ),
    ]
