# Generated by Django 4.0.5 on 2022-06-16 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0010_alter_car_fuel_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='car',
            options={'ordering': ['date']},
        ),
        migrations.AddField(
            model_name='feature',
            name='included',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='feature',
            name='price',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
