# Generated by Django 4.0.5 on 2022-06-17 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0010_remove_order_session_key_order_cars'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='ordered',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='order',
            name='total',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='orderedcar',
            name='total',
            field=models.FloatField(default=0),
        ),
    ]
