# Generated by Django 4.0.5 on 2022-06-17 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0011_car_ordered_alter_order_total_alter_orderedcar_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='number',
            field=models.BigIntegerField(default=1),
        ),
    ]
